apiVersion: v1
kind: Service
metadata:
    name: artshare-service
spec:
    type: NodePort
    selector:
        app: artshare
    ports:
        -   name: artshare-service-frontend
            protocol: TCP
            port: 80
            targetPort: 80
        -   name: artshare-service-backend
            protocol: TCP
            port: 8000
            targetPort: 8000
